"""Updated quiz attempt model

Revision ID: 65bf5a6bb3b4
Revises: 5944deb6921b
Create Date: 2024-11-28 14:31:05.512617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65bf5a6bb3b4'
down_revision = '5944deb6921b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
